config/routes.rb
Verdict::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions
  resources :problems
  
  root :to => "problems#index"
    

end

app/models/problem.rb
class Problem < ActiveRecord::Base
  attr_accessible nil
  scope :published, lambda { where("published_at < ?", Time.now) }
  
  validates_presence_of :title, :body, :time_limit, :published_at
  validates_numericality_of :time_limit, :only_integer => true, :greater_than_or_equal_to => 1
  validates_uniqueness_of :title
  
  attr_accessible :title, :body, :time_limit, :published_at, :as => :admin
  
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  attr_accessible :username, :email, :password, :password_confirmation

  validates_confirmation_of :password
  validates_presence_of :username
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def not_authenticated
    redirect_to login_url, :alert => "First login to access this page."
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  def index
    @problems = Problem.published
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Email or password was invalid"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_menu.html.erb
<div class="menu">
    <table width="100%" style="border: none;">
    <tr>
    <td style="text-align: left; vertical-align: top; border: none; word-spacing: 0.2em;">
      <%= link_to "Problems", problems_path %>
      <%= link_to "Submissions", problems_path %>
      <%= link_to "Contests", problems_path %>
      <%= link_to "Users", problems_path %>
    </td>
    <td style="text-align: right; vertical-align: top; border: none;">
      <% if current_user %>
        Logged in as <b><%= current_user.username %></b>.
        <%= link_to "Log out", logout_path %>.
      <% else %>
        You re not logged in.<br /> <%= link_to "Sign up", signup_path %> or
        <%= link_to "log in", login_path %>.
      <% end %>
    </td>
    </tr>
    </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Verdict" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
        
    
    <div class="main">
      <%= render "layouts/menu" %>
      <hr style="clear: both" />
      
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/problems/index.html.erb
<h2>Available Problems</h2>
<table>
  <tr>
    <th scope="col">Number</th>
    <th scope="col">Title</th>
    <th scope="col">Statement</th>
    <th scope="col">Submit</th>
    <th scope="col">Verdict</th>
  </tr>
  
  <% @problems.each do |problem| %>
    <tr class="<%= cycle 'odd', 'even' %>">
      <td><%= problem.id %></td>
      <td><%= problem.title %></td>
      <td><%= link_to "Problem statement", problem %></td>
      <td><%= link_to "Submit solution", problem %></td>
      <td>Not tried</td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<div class="center">
  <%= form_for @user do |f| %>
    <%= f.error_messages %>
    <div class="field">
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions"><%= f.submit %></div>
  <% end %>
</div>